--VIEW QUE MUESTRA PROYECTOS GUARDADOS
--MEGAN BOUGLE
CREATE VIEW VW_PROYECTO
AS
SELECT P.NOMBRE_PERSONA REPRESENTANTE,p.TELEFONO,E.NOMBRE_EMPRESA, PR.NOMBRE_PROYECTO ,PR.DESCRIPCION
FROM [GENERAL].[PERSONA] P INNER JOIN [GENERAL].[PROYECTO] PR
ON P.ID_PERSONA = PR.ID_PERSONA
LEFT JOIN [GENERAL].[REPRESENTANTEXEMPRESA] RXE ON P.ID_PERSONA = RXE.ID_PERSONA
LEFT JOIN [GENERAL].[EMPRESA] E ON RXE.ID_EMPRESA = E.ID_EMPRESA

