/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import Datos.DEmpresa;
import Datos.DPersona;
import Datos.DProyecto;
import Datos.DRepresentantexEmpresa;
import Datos.DSondeo;
import com.sun.jdi.connect.spi.Connection;
import entidades.Empresa;
import entidades.Persona;
import entidades.Proyecto;
import entidades.RepresentantexEmpresa;
import static formularios.FrmSondeos.jTblRegistrosSondeos;
import java.awt.HeadlessException;
import java.util.Date;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
// no se han eliminado los otros

/**
 *
 * @author Synthia Pamella
 */
public class FrmDatosProyectos extends javax.swing.JFrame {

    DEmpresa demp = new DEmpresa();
    DProyecto dpro = new DProyecto();
    DProyecto dProyecto = new DProyecto();
    DPersona dper = new DPersona();
    DRepresentantexEmpresa drexemp = new DRepresentantexEmpresa();
    TableRowSorter trsFiltro;
    DSondeo dsond = new DSondeo();

    /**
     * Creates new form FrmDatosProyectos
     */
    public FrmDatosProyectos() {
        initComponents();
        this.jTblRegistrosProyectos.setModel(dProyecto.mostrarProyectos());
        this.fillCombo();
        this.siNuevaEmpresa();
        this.fillComboRep();
        this.siNuevoRepresentante();

    }
    private Connection conn = null;
    private PreparedStatement ps = null;
    private ResultSet rs = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void buscarProyecto(String s) {
        trsFiltro = new TableRowSorter(jTblRegistrosProyectos.getModel());
        jTblRegistrosProyectos.setRowSorter(trsFiltro);
        filtrarTabla(s);
    }

    private void fillCombo() {
        jCmbEmpresas.removeAllItems();
        ArrayList<String> emp = new ArrayList<String>();
        try {
            emp = demp.listarEmpresas();
            for (String a : emp) {
                jCmbEmpresas.addItem(a);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmDatosProyectos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void fillComboRep() {
        jCmbRepresentante.removeAllItems();
        ArrayList<Persona> rep = new ArrayList<Persona>();
        try {
            rep = dper.listarRepresentante();
            for (Persona a : rep) {
                jCmbRepresentante.addItem(a);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmDatosProyectos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void siNuevoRepresentante() {
        if (jRbtnRepresentante.isSelected()) {
            jTfNombreRepresentante.setEnabled(true);
            jTfIdentificacionRepresentante.setEnabled(true);
            jTfTelefonoRepresentante.setEnabled(true);
            jTfCorreoRepresentante.setEnabled(true);
        } else {
            jTfNombreRepresentante.setEnabled(false);
            jTfIdentificacionRepresentante.setEnabled(false);
            jTfTelefonoRepresentante.setEnabled(false);
            jTfCorreoRepresentante.setEnabled(false);
        }
    }

    private void filtrarTabla(String x) {

        trsFiltro.setRowFilter(RowFilter.regexFilter(TfBuscar.getText(), 0));
        //PARA CASE SENSITIVE
        //trsFiltro.setRowFilter(RowFilter.regexFilter("(?i)"+x));

    }

    private void ubicarDatos() {
        int fila = jTblRegistrosProyectos.getSelectedRow();
        Object nombreProyecto = this.jTblRegistrosProyectos.getValueAt(fila, 0);
        Object descripcion = this.jTblRegistrosProyectos.getValueAt(fila, 1);
        Object idProyecto = this.jTblRegistrosProyectos.getValueAt(fila, 2);
        Object nombreEmpresa = this.jTblRegistrosProyectos.getValueAt(fila, 3);
        Object idEmpresa = this.jTblRegistrosProyectos.getValueAt(fila, 4);
        Object telEmpresa = this.jTblRegistrosProyectos.getValueAt(fila, 5);
        Object nombreRepresentante = this.jTblRegistrosProyectos.getValueAt(fila, 6);
        Object idRepresentante = this.jTblRegistrosProyectos.getValueAt(fila, 7);
        Object telefono = this.jTblRegistrosProyectos.getValueAt(fila, 8);
        Object correo = this.jTblRegistrosProyectos.getValueAt(fila, 9);

        String nomPro = String.valueOf(nombreProyecto);
        String des = String.valueOf(descripcion);
        String idPro = String.valueOf(idProyecto);
        String nomEmp = String.valueOf(nombreEmpresa);
        String idEmp = String.valueOf(idEmpresa);
        String telEmp = String.valueOf(telEmpresa);
        String nomRep = String.valueOf(nombreRepresentante);
        String idRep = String.valueOf(idRepresentante);
        String tel = String.valueOf(telefono);
        String email = String.valueOf(correo);

        this.jTfNombreProyecto.setText(nomPro);
        this.jTfDescripcionProyecto.setText(des);
        this.jTfIdProyecto.setText(idPro);
        this.jTfNombreEmpresa.setText(nomEmp);
        this.jTfRUC.setText(idEmp);
        this.jTfTelefonoEmpresa.setText(telEmp);
        this.jTfNombreRepresentante.setText(nomRep);
        this.jTfIdentificacionRepresentante.setText(idRep);
        this.jTfTelefonoRepresentante.setText(tel);
        this.jTfCorreoRepresentante.setText(email);

        this.jTfIdProyecto.setEnabled(false);
        this.jTfRUC.setEnabled(false);

        jBtnGuardarProyecto.setEnabled(false);
        jBtnEditar.setEnabled(true);
        jBtnEliminar.setEnabled(true);
        jBtnSondeo.setEnabled(true);
    }

    private void verificarDatosVacios() {
        if (jTfNombreProyecto.getText().equals("") || jTfNombreProyecto.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor verifique que los campos"
                    + " no esten vacíos.", "Proyectos", JOptionPane.WARNING_MESSAGE);
            jTfNombreProyecto.requestFocus();
        }
        if (jTfDescripcionProyecto.getText().equals("") || jTfDescripcionProyecto.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor verifique que los campos"
                    + " no esten vacíos.", "Proyectos", JOptionPane.WARNING_MESSAGE);
            jTfDescripcionProyecto.requestFocus();
        }

        if (jTfNombreEmpresa.getText().equals("") || jTfNombreEmpresa.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor verifique que los campos"
                    + " no esten vacíos.", "Proyectos", JOptionPane.WARNING_MESSAGE);
            jTfNombreEmpresa.requestFocus();
        }

        if (jTfTelefonoEmpresa.getText().equals("") || jTfTelefonoEmpresa.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor verifique que los campos"
                    + " no esten vacíos.", "Proyectos", JOptionPane.WARNING_MESSAGE);
            jTfTelefonoEmpresa.requestFocus();
        }

        if (jTfNombreRepresentante.getText().equals("") || jTfNombreRepresentante.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor verifique que los campos"
                    + " no esten vacíos.", "Proyectos", JOptionPane.WARNING_MESSAGE);
            jTfNombreRepresentante.requestFocus();
        }

        if (jTfTelefonoRepresentante.getText().equals("") || jTfTelefonoRepresentante.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor verifique que los campos"
                    + " no esten vacíos.", "Proyectos", JOptionPane.WARNING_MESSAGE);
            jTfTelefonoRepresentante.requestFocus();
        }
        if (jTfCorreoRepresentante.getText().equals("") || jTfCorreoRepresentante.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor verifique que los campos"
                    + " no esten vacíos.", "Proyectos", JOptionPane.WARNING_MESSAGE);
            jTfCorreoRepresentante.requestFocus();
        }

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTfIdProyecto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTfNombreProyecto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTfDescripcionProyecto = new javax.swing.JTextArea();
        jRbtnEmpresa = new javax.swing.JRadioButton();
        jCmbEmpresas = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTfNombreEmpresa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTfTelefonoEmpresa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTfRUC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTfNombreRepresentante = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTfIdentificacionRepresentante = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTfTelefonoRepresentante = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTfCorreoRepresentante = new javax.swing.JTextField();
        jBtnGuardarProyecto = new javax.swing.JButton();
        jRbtnRepresentante = new javax.swing.JRadioButton();
        jCmbRepresentante = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblRegistrosProyectos = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jBtnEditar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnSondeo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        TfBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Proyectos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(295, 295, 295))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel2.setText("Datos Generales Proyecto");

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel3.setText("ID Proyecto:");

        jTfIdProyecto.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel4.setText("Nombre:");

        jTfNombreProyecto.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel5.setText("Descripcion:");

        jTfDescripcionProyecto.setColumns(20);
        jTfDescripcionProyecto.setRows(5);
        jScrollPane2.setViewportView(jTfDescripcionProyecto);

        jRbtnEmpresa.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jRbtnEmpresa.setText("Nueva Empresa");
        jRbtnEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRbtnEmpresaMouseClicked(evt);
            }
        });
        jRbtnEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbtnEmpresaActionPerformed(evt);
            }
        });

        jCmbEmpresas.setFont(new java.awt.Font("Cambria", 0, 10)); // NOI18N
        jCmbEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbEmpresasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(354, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTfNombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTfIdProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRbtnEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCmbEmpresas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jRbtnEmpresa)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCmbEmpresas)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTfIdProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTfNombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel6.setText("Datos Generales Empresa");

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel7.setText("Nombre:");

        jTfNombreEmpresa.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel8.setText("RUC:");

        jTfTelefonoEmpresa.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel9.setText("Telefono:");

        jTfRUC.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jTfRUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfRUCActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel10.setText("Datos Generales Representante");

        jLabel11.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel11.setText("Nombre:");

        jTfNombreRepresentante.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel12.setText("Identificacion:");

        jTfIdentificacionRepresentante.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel13.setText("Telefono:");

        jTfTelefonoRepresentante.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel14.setText("Correo:");

        jTfCorreoRepresentante.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        jBtnGuardarProyecto.setBackground(new java.awt.Color(102, 102, 102));
        jBtnGuardarProyecto.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jBtnGuardarProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complementos/img/guardarFI.png"))); // NOI18N
        jBtnGuardarProyecto.setText("Guardar");
        jBtnGuardarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarProyectoActionPerformed(evt);
            }
        });

        jRbtnRepresentante.setText("Nuevo Representante");
        jRbtnRepresentante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRbtnRepresentanteMouseClicked(evt);
            }
        });
        jRbtnRepresentante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbtnRepresentanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnGuardarProyecto))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 64, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTfRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTfNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTfTelefonoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTfNombreRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTfIdentificacionRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTfTelefonoRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTfCorreoRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jCmbRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRbtnRepresentante))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTfNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTfRUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTfTelefonoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jRbtnRepresentante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCmbRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTfNombreRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfIdentificacionRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTfTelefonoRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTfCorreoRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnGuardarProyecto)
                .addGap(6, 6, 6))
        );

        jTblRegistrosProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTblRegistrosProyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblRegistrosProyectosMouseClicked(evt);
            }
        });
        jTblRegistrosProyectos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTblRegistrosProyectosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTblRegistrosProyectos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jBtnEditar.setBackground(new java.awt.Color(255, 153, 51));
        jBtnEditar.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jBtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complementos/img/editarFI.png"))); // NOI18N
        jBtnEditar.setText("Editar");
        jBtnEditar.setEnabled(false);
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        jBtnEliminar.setBackground(new java.awt.Color(255, 153, 51));
        jBtnEliminar.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jBtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complementos/img/eliminarFI.png"))); // NOI18N
        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.setEnabled(false);
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });

        jBtnSondeo.setBackground(new java.awt.Color(255, 153, 51));
        jBtnSondeo.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jBtnSondeo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complementos/img/sondeosFI.png"))); // NOI18N
        jBtnSondeo.setText("Sondeos");
        jBtnSondeo.setEnabled(false);
        jBtnSondeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSondeoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnEditar)
                .addGap(18, 18, 18)
                .addComponent(jBtnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnSondeo)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEditar)
                    .addComponent(jBtnEliminar)
                    .addComponent(jBtnSondeo))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jLabel16.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel16.setText("Buscar:");

        TfBuscar.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        TfBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfBuscarActionPerformed(evt);
            }
        });
        TfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(TfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTfRUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfRUCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfRUCActionPerformed
    private void siNuevaEmpresa() {
        if (jRbtnEmpresa.isSelected()) {
            jTfNombreEmpresa.setEnabled(true);
            jTfRUC.setEnabled(true);
            jTfTelefonoEmpresa.setEnabled(true);
        } else {
            jTfNombreEmpresa.setEnabled(false);
            jTfRUC.setEnabled(false);
            jTfTelefonoEmpresa.setEnabled(false);
        }
    }

    private void limpiar() {
        jTfNombreEmpresa.setText("");
        jTfRUC.setText("");
        jTfTelefonoEmpresa.setText("");
        jTfIdProyecto.setText("");
        jTfNombreProyecto.setText("");
        jTfDescripcionProyecto.setText("");
        jTfIdentificacionRepresentante.setText("");
        jTfNombreRepresentante.setText("");
        jTfCorreoRepresentante.setText("");
        jTfTelefonoRepresentante.setText("");
    }

    private String obtIdRep(String item) {
        int pos = item.indexOf(": ");
        System.out.println("inicio: " + pos);
        String subcad = item.substring(pos + 2);

        return subcad;
    }


    private void jBtnGuardarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarProyectoActionPerformed
        // TODO add your handling code here:
        try {
            // Obtenemos los datos de los textfields
            String nombreEmpresa = jTfNombreEmpresa.getText();
            String ruc = jTfRUC.getText();
            String telefonoEmp = jTfTelefonoEmpresa.getText();
            Empresa emp = new Empresa(ruc, nombreEmpresa, telefonoEmp);
            String idPro = jTfIdProyecto.getText();
            String nombreProyecto = jTfNombreProyecto.getText();
            String desc = jTfDescripcionProyecto.getText();
            String idPer = jTfIdentificacionRepresentante.getText();
            String nomrep = jTfNombreRepresentante.getText();
            String correo = jTfCorreoRepresentante.getText();
            String telefono = jTfTelefonoRepresentante.getText();

            Persona per = new Persona(nomrep, idPer, correo, telefono);

            RepresentantexEmpresa rexemp = new RepresentantexEmpresa(ruc, idPer);
            Proyecto pro = new Proyecto(nombreProyecto, idPro, desc, rexemp);
            // validamos que el id del proyecto sea nuevo, si ya esta en uso, limpia tf y se sale.
            if (dpro.inProyecto(idPro)) {
                JOptionPane.showMessageDialog(this, "ID de proyecto en uso!");
                limpiar();
                return;
            }
            // verificamos si vamos a registrar nueva empresa o usaremos una existente
            if (jRbtnEmpresa.isSelected()) {
                if (demp.inEmpresa(ruc)) { // si el id existe, limpia tf y sale
                    JOptionPane.showMessageDialog(this, "Empresa ya existente!");
                    limpiar();
                    return;
                }
                demp.guardarEmpresa(emp); // en este caso, agrega la empresa a la bd
                if (!jRbtnRepresentante.isSelected()) {
                    idPer = obtIdRep(jCmbRepresentante.getSelectedItem().toString());
                    per.setID_Persona(idPer);
                    rexemp.setIDPersona(idPer); // obtenemos información del combo box y actualizamos los objetos
                } else {
                    if (!dper.inPersona(idPer)) { // si no esta en registros, entonces agrega a persona y representante
                        dper.guardarPersona(per, 3); // guarda en persona
                        dper.guardarPersona(per, 1); // guarda en representante
                    } else if (!dper.inRepresentante(idPer)) {
                        dper.guardarPersona(per, 1); // guarda solamente en rep, porque estaba en ensayista y persona
                    } else {
                        JOptionPane.showMessageDialog(this, "Has ingresado "
                                + "una identificación"
                                + " de una persona registrada!");
                        limpiar();
                        return;
                    }
                }
                /*if (!dper.inPersona(idPer)) {
                    dper.guardarPersona(per, 3);
                    dper.guardarPersona(per, 1);
                } else if (!dper.inRepresentante(idPer)) {
                    dper.guardarPersona(per, 1);
                }*/
                // verificar si la persona está vinculada con otra empresa y activo
                drexemp.vincEmpxRep(idPer);
                // si lo está, actualizar fecha fin de representantexempresa where id = al de la persona
                // si no, procede

                drexemp.guardarRexEmp(rexemp);
                dpro.guardarProyecto(pro);
                JOptionPane.showMessageDialog(this, "Registro Guardado.",
                        "Proyectos", JOptionPane.INFORMATION_MESSAGE);

            } else {
                nombreEmpresa = jCmbEmpresas.getSelectedItem().toString();
                ruc = demp.getEmpId(nombreEmpresa);
                emp.setID_Empresa(ruc);
                rexemp.setIDEmpresa(ruc);

                if (!jRbtnRepresentante.isSelected()) {
                    idPer = obtIdRep(jCmbRepresentante.getSelectedItem().toString());
                    per.setID_Persona(idPer);
                    rexemp.setIDPersona(idPer);
                } else {
                    if (!dper.inPersona(idPer)) {
                        dper.guardarPersona(per, 3);
                        dper.guardarPersona(per, 1);
                    } else if (!dper.inRepresentante(idPer)) {
                        dper.guardarPersona(per, 1);
                    } else {
                        JOptionPane.showMessageDialog(this, "Has ingresado "
                                + "una identificación"
                                + " de una persona registrada!");
                        limpiar();
                        return;
                    }
                }

                // estoy ingresando una persona a un empresa especifica
                // tengo id empresa = ruc y se que está en los registros
                // tengo persona, que tiene idPer y no se que pasa con ella todavia
                // la persona que ingreso no tiene registro con ninguna empresa
                // la pareja (idPer, emp) no esta en repxemp -> solamente se agrega
                // la persona que ingreso tiene un registro con la empresa y se encuentra activa
                // no hago nada
                // cuando ! condicion anterior tengo que hacer update
                drexemp.updateEmpxRep(ruc, idPer, true);
                if (!drexemp.activoInRepxEmp(idPer, ruc)) {
                    // si no esta activa en la empresa vamos a realizar los update
                    if (drexemp.existeRepxEmp(idPer, ruc)) { // si existiese un registro, entonces idPer - ruc - not null
                        // revisamos si existe un registro, significa que está inactiva
                        drexemp.updateEmpxRep(ruc, idPer, false);
                    } else {
                        // la pareja (idPer, ruc) no se encuentra registrada, entonces la registramos
                        drexemp.guardarRexEmp(rexemp);
                    }
                }
                dpro.guardarProyecto(pro);
                JOptionPane.showMessageDialog(this, "Registro Guardado.",
                        "Proyectos", JOptionPane.INFORMATION_MESSAGE);
            }
            this.fillCombo();
            this.limpiar();
            this.fillComboRep();
            this.jTblRegistrosProyectos.setModel(dProyecto.mostrarProyectos());
            this.verificarDatosVacios();

        } catch (HeadlessException ex) {
            System.out.println("Error al intentar guardar: " + ex.getMessage());
        }
    }//GEN-LAST:event_jBtnGuardarProyectoActionPerformed

    private void TfBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfBuscarKeyReleased
        // TODO add your handling code here:
        String buscarPj = TfBuscar.getText();
        buscarProyecto(buscarPj);
    }//GEN-LAST:event_TfBuscarKeyReleased

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        // TODO add your handling code here:
        String nombreEmpresa = jTfNombreEmpresa.getText();
        String ruc = jTfRUC.getText();
        String telefonoEmp = jTfTelefonoEmpresa.getText();
        Empresa emp = new Empresa(ruc, nombreEmpresa, telefonoEmp);
        String idPro = jTfIdProyecto.getText();
        String nombreProyecto = jTfNombreProyecto.getText();
        String desc = jTfDescripcionProyecto.getText();
        String idPer = jTfIdentificacionRepresentante.getText();
        String nomrep = jTfNombreRepresentante.getText();
        String correo = jTfCorreoRepresentante.getText();
        String telefono = jTfTelefonoRepresentante.getText();

        Persona per = new Persona(nomrep, idPer, correo, telefono);
        RepresentantexEmpresa rexemp = new RepresentantexEmpresa(ruc, idPer);
        Proyecto pro = new Proyecto(nombreProyecto, idPro, desc, rexemp);
        dpro.updateProyecto(pro, per, emp);

        this.fillCombo();
        this.limpiar();
        this.fillComboRep();
        this.jTblRegistrosProyectos.setModel(dProyecto.mostrarProyectos());
        jTblRegistrosProyectos.clearSelection();
        regSelected();
        jBtnEditar.setEnabled(false);
        jBtnEliminar.setEnabled(false);
        jBtnSondeo.setEnabled(false);
        jBtnGuardarProyecto.setEnabled(true);
        jTfRUC.setEnabled(true);
        jTfIdProyecto.setEnabled(true);
        jTfIdentificacionRepresentante.setEnabled(true);
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jTblRegistrosProyectosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblRegistrosProyectosKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            ubicarDatos();
        }
    }//GEN-LAST:event_jTblRegistrosProyectosKeyReleased

    private void jTblRegistrosProyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblRegistrosProyectosMouseClicked
        // TODO add your handling code here:
        ubicarDatos();
        regSelected();
    }//GEN-LAST:event_jTblRegistrosProyectosMouseClicked

    private void jBtnSondeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSondeoActionPerformed
        // TODO add your handling code here:
        FrmSondeos frm2 = new FrmSondeos();
        frm2.setVisible(true);
        this.setVisible(false);
        FrmSondeos.jTfIdProyect.setText(this.jTfIdProyecto.getText());
        FrmSondeos.jTfNomProyecto.setText(this.jTfNombreProyecto.getText());
        //mostramos la tabla de sondeos
        FrmSondeos.jTblRegistrosSondeos.setModel(dsond.mostrarSondeos(FrmSondeos.jTfIdProyect.getText()));
    }//GEN-LAST:event_jBtnSondeoActionPerformed

    private void TfBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfBuscarActionPerformed

    private void jRbtnEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbtnEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbtnEmpresaActionPerformed

    private void jCmbEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbEmpresasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbEmpresasActionPerformed

    private void jRbtnEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRbtnEmpresaMouseClicked
        // TODO add your handling code here:
        this.siNuevaEmpresa();
    }//GEN-LAST:event_jRbtnEmpresaMouseClicked

    private void jTblRegistrosProyectosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTblRegistrosProyectosPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTblRegistrosProyectosPropertyChange

    private void jTblRegistrosProyectosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblRegistrosProyectosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTblRegistrosProyectosKeyPressed

    private void jTblRegistrosProyectosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblRegistrosProyectosMousePressed
        // TODO add your handling code here
    }//GEN-LAST:event_jTblRegistrosProyectosMousePressed

    private void jTblRegistrosProyectosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblRegistrosProyectosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jTblRegistrosProyectosMouseExited

    private void regSelected() {
        if (jTblRegistrosProyectos.getSelectedRowCount() > 0) {
            jRbtnEmpresa.setEnabled(true);
            jRbtnRepresentante.setEnabled(true);
            jRbtnEmpresa.hide();
            jRbtnRepresentante.hide();
            jTfNombreEmpresa.setEnabled(true);
            jTfTelefonoEmpresa.setEnabled(true);
            jTfTelefonoRepresentante.setEnabled(true);
            jTfNombreRepresentante.setEnabled(true);
            jTfCorreoRepresentante.setEnabled(true);
        } else {
            jRbtnEmpresa.show();
            jRbtnRepresentante.show();
        }
    }

    private void jRbtnRepresentanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRbtnRepresentanteMouseClicked
        // TODO add your handling code here:
        this.siNuevoRepresentante();

    }//GEN-LAST:event_jRbtnRepresentanteMouseClicked

    private void jRbtnRepresentanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbtnRepresentanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbtnRepresentanteActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        // TODO add your handling code here:
         this.verificarDatosVacios();
        int resp = JOptionPane.showConfirmDialog(this, "¿Desea eliminar este proyecto?",
                "Proyecto",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(resp ==0){
            if(dProyecto.eliminarProyecto(jTfIdProyecto.getText())){
                JOptionPane.showMessageDialog(this, "Proyecto Eliminado",
                        "Proyecto",JOptionPane.INFORMATION_MESSAGE);
                limpiar();
            }
            else{
                JOptionPane.showMessageDialog(this, "Error al eliminar",
                        "Proyecto",JOptionPane.WARNING_MESSAGE);
            }
        }
       this.jTblRegistrosProyectos.setModel(dProyecto.mostrarProyectos());
       jTblRegistrosProyectos.clearSelection();
        limpiar();
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDatosProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDatosProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDatosProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDatosProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDatosProyectos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TfBuscar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnGuardarProyecto;
    private javax.swing.JButton jBtnSondeo;
    private javax.swing.JComboBox<String> jCmbEmpresas;
    private javax.swing.JComboBox<Persona> jCmbRepresentante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRbtnEmpresa;
    private javax.swing.JRadioButton jRbtnRepresentante;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTblRegistrosProyectos;
    private javax.swing.JTextField jTfCorreoRepresentante;
    private javax.swing.JTextArea jTfDescripcionProyecto;
    public static javax.swing.JTextField jTfIdProyecto;
    private javax.swing.JTextField jTfIdentificacionRepresentante;
    private javax.swing.JTextField jTfNombreEmpresa;
    private javax.swing.JTextField jTfNombreProyecto;
    private javax.swing.JTextField jTfNombreRepresentante;
    private javax.swing.JTextField jTfRUC;
    private javax.swing.JTextField jTfTelefonoEmpresa;
    private javax.swing.JTextField jTfTelefonoRepresentante;
    // End of variables declaration//GEN-END:variables
}
