/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import Datos.DMuestra;
import Datos.DMuestraxTamiz;
import Datos.DPersona;
import Datos.DTamiz;
import entidades.Muestra;
import entidades.MuestraxTamiz;
import entidades.Persona;
import entidades.Sondeo;
import entidades.Tamiz;
import static formularios.FrmSondeos.jTblRegistrosSondeos;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ale05
 */
public class FrmMuestras extends javax.swing.JFrame {

    /**
     * Creates new form FrmMuestras
     */
    public FrmMuestras() {
        initComponents();
        jTfIdSondeo.setEnabled(false);
        fillCombo();
    }
    
    DPersona dper = new DPersona();
    DMuestra dmues = new DMuestra();
    DTamiz dtam = new DTamiz();
    DMuestraxTamiz dmxt = new DMuestraxTamiz();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTfIdMuestra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTfEnsayista = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTfIdEnsayista = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblMuestras = new javax.swing.JTable();
        jBtnGuardarAM = new javax.swing.JButton();
        jBtnEditarAM = new javax.swing.JButton();
        jBtnEliminarAM = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTfIdSondeo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTfTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTfCorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTfPesoInicial = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblGranulometria = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTfPesoRet = new javax.swing.JTextField();
        jCmbTam = new javax.swing.JComboBox<>();
        jBtnGuardarG = new javax.swing.JButton();
        jBtnEditarG = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTfPesoFinal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Muestra:");

        jTfIdMuestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfIdMuestraActionPerformed(evt);
            }
        });

        jLabel2.setText("Muestreado por:");

        jLabel3.setText("Identificacion");

        TblMuestras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TblMuestras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblMuestrasMouseClicked(evt);
            }
        });
        TblMuestras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TblMuestrasKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(TblMuestras);

        jBtnGuardarAM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complementos/img/guardarFI.png"))); // NOI18N
        jBtnGuardarAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarAMActionPerformed(evt);
            }
        });

        jBtnEditarAM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complementos/img/editarFI.png"))); // NOI18N
        jBtnEditarAM.setEnabled(false);

        jBtnEliminarAM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complementos/img/eliminarFI.png"))); // NOI18N
        jBtnEliminarAM.setEnabled(false);

        jLabel6.setText("Sondeo:");

        jLabel7.setText("Telefono:");

        jTfTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfTelefonoActionPerformed(evt);
            }
        });

        jLabel8.setText("Correo: ");

        jTfCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfCorreoActionPerformed(evt);
            }
        });

        jLabel9.setText("Peso Inicial: ");

        jTfPesoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfPesoInicialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jBtnGuardarAM)
                                        .addGap(39, 39, 39)
                                        .addComponent(jBtnEditarAM)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBtnEliminarAM))
                                    .addComponent(jTfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(579, 579, 579)
                                .addComponent(jTfPesoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(237, 237, 237)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTfIdMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTfIdSondeo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTfIdEnsayista, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTfEnsayista, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(82, 82, 82))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jTfIdMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTfPesoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfIdSondeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jTfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnEditarAM)
                            .addComponent(jBtnGuardarAM)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jTfIdEnsayista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBtnEliminarAM)))
                    .addComponent(jTfEnsayista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Agregar Muestras", jPanel2);

        TblGranulometria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TblGranulometria);

        jLabel4.setText("Peso Retenido por el Tamiz:");

        jCmbTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbTamActionPerformed(evt);
            }
        });

        jBtnGuardarG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complementos/img/guardarFI.png"))); // NOI18N
        jBtnGuardarG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarGActionPerformed(evt);
            }
        });

        jBtnEditarG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complementos/img/editarFI.png"))); // NOI18N

        jLabel5.setText("Peso Final");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTfPesoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbTam, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTfPesoRet, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jBtnGuardarG)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnEditarG)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfPesoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jBtnGuardarG))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBtnEditarG)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jCmbTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfPesoRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Granulometria", jPanel1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complementos/img/regresar.png"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCmbTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbTamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbTamActionPerformed

    private void jBtnGuardarAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarAMActionPerformed
        // TODO add your handling code here:
        String idMuestra = jTfIdMuestra.getText();
        String idSondeo = jTfIdSondeo.getText();
        double pesoin = Double.parseDouble(jTfPesoInicial.getText());
// guardar
        String nomEnsayista = jTfEnsayista.getText();
        String idEnsayista = jTfIdEnsayista.getText();
        String tel = jTfTelefono.getText();
        String correo = jTfCorreo.getText();
        
        Sondeo son = new Sondeo(idSondeo);
        
        Persona per = new Persona(nomEnsayista, idEnsayista, correo, tel);
        
        Muestra mues = new Muestra(idMuestra, pesoin, son, per);
        if (!dper.inPersona(idEnsayista)) {
            dper.guardarPersona(per, 3);
            dper.guardarPersona(per, 2);
        } else if (!dper.inEnsayista(idEnsayista)) {
            dper.guardarPersona(per, 2);
        }
        dmues.guardarMuestra1(mues);
        TblMuestras.setModel(dmues.mostrarMuestras(idSondeo));
        limpiar();
    }//GEN-LAST:event_jBtnGuardarAMActionPerformed
    private void limpiar() {
        jTfIdMuestra.setText("");
        jTfIdSondeo.setText("");
        jTfEnsayista.setText("");
        jTfIdEnsayista.setText("");
        jTfTelefono.setText("");
        jTfCorreo.setText("");
    }
    
    private void ubicarDatosSondeos() {
        
        int fila = TblMuestras.getSelectedRow();
        Object idMuestra = this.TblMuestras.getValueAt(fila, 0);
        Object pesoInicial = this.TblMuestras.getValueAt(fila, 1);
        Object pesoFinal = this.TblMuestras.getValueAt(fila, 2);
        Object identificacionEn = this.TblMuestras.getValueAt(fila, 3);
        Object nombreEnsayista = this.TblMuestras.getValueAt(fila, 4);
        Object correoE = this.TblMuestras.getValueAt(fila, 5);
        Object telefono = this.TblMuestras.getValueAt(fila, 6);
        
        String id = String.valueOf(idMuestra);
        String peso = String.valueOf(pesoInicial);
        String pesoF = String.valueOf(pesoFinal);
        String idE = String.valueOf(identificacionEn);
        String nombreE = String.valueOf(nombreEnsayista);
        String correo = String.valueOf(correoE);
        String telefonoE = String.valueOf(telefono);
        
        this.jTfCorreo.setText(correo);
        this.jTfEnsayista.setText(nombreE);
        this.jTfIdMuestra.setText(id);
        this.jTfPesoFinal.setText(peso);
        this.jTfIdEnsayista.setText(idE);
        this.jTfTelefono.setText(telefonoE);
        //this.jtf

        // this.jTfCoordenadasSondeo.setText(coordenadasSondeo);
        // jTfCoordenadasSondeo.setEditable(false);
        // this.jTfFechaSondeo.setText(fechaSondeo);
        jBtnGuardarAM.setEnabled(false);
        jBtnEditarAM.setEnabled(true);
        jBtnEliminarAM.setEnabled(true);
        
    }
    private void jTfIdMuestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfIdMuestraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfIdMuestraActionPerformed

    private void jTfTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfTelefonoActionPerformed

    private void jTfCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfCorreoActionPerformed

    private void TblMuestrasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TblMuestrasKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            ubicarDatosSondeos();
        }
    }//GEN-LAST:event_TblMuestrasKeyReleased

    private void TblMuestrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblMuestrasMouseClicked
        // TODO add your handling code here:
        ubicarDatosSondeos();
    }//GEN-LAST:event_TblMuestrasMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmSondeos frmReg3 = new FrmSondeos();
        frmReg3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTfPesoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfPesoInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfPesoInicialActionPerformed

    private void jBtnGuardarGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarGActionPerformed
        // TODO add your handling code here:
        String tamiz = jCmbTam.getSelectedItem().toString();
        double peso_ret = Double.parseDouble(jTfPesoRet.getText());
        String id_muestra = jTfIdMuestra.getText();
        Tamiz tam = dtam.genTamiz(tamiz);
        Muestra mues = new Muestra(id_muestra);
        MuestraxTamiz mxt = new MuestraxTamiz(peso_ret, tam, mues); 
        dmxt.agregarMuestraxTamiz(mxt);    
    }//GEN-LAST:event_jBtnGuardarGActionPerformed

    private void fillCombo() {
        jCmbTam.removeAllItems();
        ArrayList<Tamiz> tam = new ArrayList<Tamiz>();
        try {
            tam = dtam.listarTam();
            for (Tamiz a : tam) {
                jCmbTam.addItem(a);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmDatosProyectos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMuestras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMuestras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMuestras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMuestras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMuestras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblGranulometria;
    public static javax.swing.JTable TblMuestras;
    private javax.swing.JButton jBtnEditarAM;
    private javax.swing.JButton jBtnEditarG;
    private javax.swing.JButton jBtnEliminarAM;
    private javax.swing.JButton jBtnGuardarAM;
    private javax.swing.JButton jBtnGuardarG;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Tamiz> jCmbTam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTfCorreo;
    private javax.swing.JTextField jTfEnsayista;
    private javax.swing.JTextField jTfIdEnsayista;
    private javax.swing.JTextField jTfIdMuestra;
    public static javax.swing.JTextField jTfIdSondeo;
    private javax.swing.JTextField jTfPesoFinal;
    private javax.swing.JTextField jTfPesoInicial;
    private javax.swing.JTextField jTfPesoRet;
    private javax.swing.JTextField jTfTelefono;
    // End of variables declaration//GEN-END:variables
}
